experiment_name: charnn-test
mlflow_server_url: http://127.0.0.1:5000  # http://54.184.87.80:8888 # Local: http://34.210.192.64:5000
opt:
  lr: 0.0006
  weight_decay: 0.1
dataset:
  path: data/input.txt  # s3://charnn-data/data/input.txt 
max_iter: 2
trainer:
  max_epochs: 1
  lr: 0.0006
  batch_size: 128 # 216
  data_loader_workers: 1
  enable_profile: False
  # checkpoint_path
  # log_dir
model:
  n_layer: 2 # 8
  n_head: 2 # 8
  n_embd: 32 # 512
charnn:
  # ddp, fsdp
  dist: ddp
  # train or generate
  task: train
  # start string
  phrase: Hello there

hydra:
  run:
    dir: ./

